version: "3"

vars:
  STATIC_DIR: "static/css"
  DAISYUI_VERSION: "v5.5.18"

tasks:
  install:all:
    desc: Install all dependencies
    cmds:
      - go mod tidy
      - task: install:daisyui

  install:daisyui:
    desc: Download DaisyUI plugin files
    cmds:
      - curl -sL -o {{.STATIC_DIR}}/daisyui.mjs https://github.com/saadeghi/daisyui/releases/download/{{.DAISYUI_VERSION}}/daisyui.mjs
      - curl -sL -o {{.STATIC_DIR}}/daisyui-theme.mjs https://github.com/saadeghi/daisyui/releases/download/{{.DAISYUI_VERSION}}/daisyui-theme.mjs
    status:
      - test -f {{.STATIC_DIR}}/daisyui.mjs
      - test -f {{.STATIC_DIR}}/daisyui-theme.mjs

  install:playwright:
    desc: Install Playwright
    cmds:
      - npm install -g playwright
      - playwright install

  install:datastar:
    desc: Install Datastar
    cmds:
      - curl -sL -o {{.STATIC_DIR}}/datastar.js https://cdn.jsdelivr.net/gh/starfederation/datastar@1.0.0-RC.7/bundles/datastar.js
    status:
      - test -f {{.STATIC_DIR}}/datastar.js


  # The `build:` tasks below are used together for production builds of a project
  build:templ:
    cmds:
      - go tool templ generate
    sources:
      - "**/*.templ"
    generates:
      - "**/*_templ.go"

  build:web:styles:
    cmds:
      - go tool gotailwind -i {{.STATIC_DIR}}/input.css -o {{.STATIC_DIR}}/output.css
    sources:
      - "./web/resources/**/*.{html,ts,templ,go,css}"
    generates:
      - "{{.STATIC_DIR}}/index.css"

  build:
    cmds:
      - go build -tags=prod -o bin/showcase ./cmd/showcase
    deps:
      - build:templ
      - build:web:styles
