version: "3"

tasks:
  templui:add:
    desc: Add all templui components
    cmds:
      - go tool templui add "*"

  install:all:
    desc: Install all dependencies
    cmds:
      - go mod tidy
      - go tool templui -force init
      - go tool templui -force add "*"
